language: node_js
node_js:
  - "6.9"
  - "7.5"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - "yarn run test-ci"
after_script:
  - "yarn add coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"

